config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/hanship0530/Learning
      targetRevision: main

applications:
  - name: helm-guestbook
    path: ci-cd-cookbook/6w/helm-guestbook
    tool:
      helm:
        releaseName: helm-guestbook
  - name: kustomize-guestbook
    path: ci-cd-cookbook/6w/kustomize-guestbook
  - name: sync-waves
    path: ci-cd-cookbook/6w/sync-waves