config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/gasida/cicd-study
      targetRevision: main

applications:
  - name: ci-cd-cookbook/6w/helm-guestbook
    tool:
      helm:
        releaseName: helm-guestbook
  - name: ci-cd-cookbook/6w/kustomize-guestbook
  - name: ci-cd-cookbook/6w/sync-waves
