apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "pacman.selectorLabels" . | nindent 6 }}
  name: {{ .Chart.Name }}
spec:
  ports:
    - name: http
      port: {{ .Values.image.containerPort }}
      targetPort: {{ .Values.image.containerPort }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
